name: Jobs in Container 
on: workflow_dispatch
jobs:
  container:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    services:
      node:
        image: nginx:latest
        ports: 
          - 80:80
    steps:
      - name: Print Dummy Text
        run: echo "Hellow World!"
      - name: Curl Command
        run: curl -v -k node:80
