name: Output Information
on: 
  push:
    branches:
    - main
  workflow_dispatch:
env:
  FIRST_ENV: "Hello World"
jobs:
   build: 
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Output Github Context
        run: |
          pwd
          echo "$FIRST_ENV" >> test.txt
          echo "${{ secrets.MY_SECRET }}" > test.txt
          echo "${{ secrets.PASSWORD }}" > test.txt
      - name: Cache Files
        uses: actions/cache@v4.0.0
        with: 
          path: ./
          key: workflows-${{ hashFiles('README.md') }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: dist-files
          path: |
           test.txt
   download:
     runs-on: ubuntu-latest
     needs: [build]
     steps:
       - name: Download Artifacts
         uses: actions/download-artifact@v4.1.2
         with:
           name: dist-files
           path: |
             test.txt
       - name: Simulate Error
         run: exit -1
         id: simulate-error
       - name: Execute Upon Failure
         if: failure() && steps.simulate-error.outcome == 'failure'
         run: echo "This catches failure"
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Simulate Error
         run: exit -1
         continue-on-error: true
       - name: Deploy
         run: echo "Contunie on Error"
         
        
      
