name: Output Information
on: 
  push:
    branches:
    - main
  workflow_dispatch:
env:
  FIRST_ENV: "Hello World"
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: |
          pwd
          echo "$FIRST_ENV" >> test.txt
      - name: Cache Files
        uses: actions/cache@v4.0.0
        with: 
          path: ./
          key: workflows-${{ hashFiles('README.md')}}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: dist-files
          path: |
           test.txt
  download:
     runs-on: ubuntu-latest
     needs: [info]
     steps:
       - name: Download Artifacts
         uses: actions/download-artifact@v4.1.2
         with:
           name: dist-files
           path: |
             test.txt
