name: Sixth Workflow
on: workflow_dispatch
jobs:
  self_host_job:
    runs-on: self-hosted
    container: 
      image: node:20
    steps:
      - name: Print Dummy Text
        run: echo "Hello World!"
      - name: Get code
        uses: actions/checkout@3
